In [1]:
import tensorflow as tf

# Example params tensor with shape [batch_size, height, width]
params = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

print(params.shape)
#the batch size is like our n
# Example indices tensor with shape [batch_size, num_elements]
indices = tf.constant([
    [0, 1],
    [1, 0],
    [0, 0]
])

# Using tf.gather with batch_dims
result = tf.gather(params, indices, batch_dims=1)

print(result)


(3, 2, 2)
tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 7  8]
  [ 5  6]]

 [[ 9 10]
  [ 9 10]]], shape=(3, 2, 2), dtype=int32)
